### ISSUE TITLE
How to make multi-part/form-data request in runtime?

### ISSUE THREAD

**Issue by Ansh-Rathod** [invertase/dart_edge#22]
Hey guys, loving this package in the edge function. but any plans to add muliPartRequest to the package?

**Comment by Ehesp** [comment]
@Ansh-Rathod ill have to investigate, however it should theoretically work, have you tried? 

Cc @lesnitsky

**Comment by Ansh-Rathod** [comment]
> @Ansh-Rathod ill have to investigate, however it should theoretically work, have you tried? 
> 
> Cc @lesnitsky
> 
> 

yeah, i tried this, the major issue i think is it didn't added proper headers to request. every time headers was empty and response became 400 bad request.

**Comment by Ehesp** [comment]
Could you share the code? Will add a test case

**Comment by MichealReed** [comment]
@Ansh-Rathod how did you get this working? I can't find MultipartRequest anywhere in the edge library using the traditional http lib triggers 
```
<ref *1> UnsupportedError {
  message: "Cannot create a client without dart:html or dart:io.",
  "$thrownJsError": <ref *2> Unsupported operation: Cannot create a client without dart:html or dart:io.
    at Object.wrapException (file:///src/main.dart.js:698:17)
    at Object.throwExpression (file:///src/main.dart.js:712:15)
    at Object.createClient (file:///src/main.dart.js:6951:16)
    at Object.Client_Client (file:///src/main.dart.js:6947:18)
    at file:///src/main.dart.js:13071:26
    at _wrapJsFunctionForAsync_closure.$protected (file:///src/main.dart.js:3324:15)
    at _wrapJsFunctionForAsync_closure.call$2 (file:///src/main.dart.js:8780:12)
    at Object._asyncStartSync (file:///src/main.dart.js:3288:20)
    at MultipartRequest.send$0 (file:///src/main.dart.js:13076:16)
    at file:///src/main.dart.js:14098:48 {
    dartException: [Circular *1],
    name: "",
    "$cachedTrace": _StackTrace { _exception: [Circular *2], _trace: null }
  }
}
```

**Comment by MichealReed** [comment]
> well, if you use runtimeclient with HTTP library.

The problem is not with http, but the missing html/io libraries. Are you sure you got this working? Could you please share code? If it wasn't working for you please say so Invertase can prioritize this to be fixed.

I tried with 

`http.runWithClient(() => getResponse, () => EdgeHttpClient());`

as well.

Any thoughts @Ehesp?
