### ISSUE TITLE
[BUG] Supabase: Cannot read request.body contents

### ISSUE THREAD

**Issue by henry2man** [invertase/dart_edge#40]
In Supabase functions `Request.body` cannot be read ever.

Taking this as a base example it always return "`Body not used`" (independently if you send body in your post request or not:

Example cURL: 
```bash
curl  -X POST -d '{"message":"This is a test"}' http://localhost:54321/functions/v1/dart_edge
```

`main.dart`

```dart
import 'package:supabase_functions/supabase_functions.dart';

void main() {
  SupabaseFunctions(fetch: (request) {
    if (request.bodyUsed) {
      return Response("Body used! - Contents: ${request.body}");
    } else {
      return Response("Body not used");
    }
  });
}
```

If you try to read the body directly there is an error: 

```dart
import 'package:supabase_functions/supabase_functions.dart';

void main() {
  SupabaseFunctions(fetch: (request) {
    if (request.body != null) { // accesing body directly
      return Response("Body used! - Contents: ${request.body}");
    } else {
      return Response("Body not used");
    }
  });
}
```

```js
UnknownJsTypeError {
  "__js_helper$_message": "ReadableStream is locked.",
  "$thrownJsError": TypeError: ReadableStream is locked.
    at setUpReadableStreamDefaultReader (internal:ext/web/06_streams.js:3357:13)
    at new ReadableStreamDefaultReader (internal:ext/web/06_streams.js:4933:7)
    at acquireReadableStreamDefaultReader (internal:ext/web/06_streams.js:297:12)
    at ReadableStream.getReader (internal:ext/web/06_streams.js:4781:16)
    at Request.get$body (file:///home/deno/functions/dart_edge/main.dart.js:7414:89)
    at main_closure.call$1 (file:///home/deno/functions/dart_edge/main.dart.js:7424:68)
    at file:///home/deno/functions/dart_edge/main.dart.js:7466:60
    at _wrapJsFunctionForAsync_closure.$protected (file:///home/deno/functions/dart_edge/main.dart.js:2948:15)
    at _wrapJsFunctionForAsync_closure.call$2 (file:///home/deno/functions/dart_edge/main.dart.js:5575:12)
    at Object._asyncStartSync (file:///home/deno/functions/dart_edge/main.dart.js:2912:20)
}
```

**Comment by henry2man** [comment]
I don't have my computer right now but as far as I remember `json()` also failed. I'll try to check later.

Nevertheless json alternative won't work for non json (plain text, binary, multipart...) bodies 😁

**Comment by henry2man** [comment]
Oh I just noticed that @lesnitsky already solved this one on the PR, kudos!! 😊

**Comment by henry2man** [comment]
Confirmed: #41 fixes this one.

For anyone trying, this is how can you apply the patch for now: in `pubspec.yaml` you need to override `edge_rutime`:

```
dependency_overrides: 
  edge_runtime: 
    git:
      url: https://github.com/invertase/dart_edge.git
      ref: fix/request-body-access
      path: packages/edge_runtime

```
