### ISSUE TITLE
Can't deploy my function: Error: NotFound: No such file or directory

### ISSUE THREAD

**Issue by agordeev** [invertase/dart_edge#59]
Executing this:

    supabase functions deploy dart_edge --debug

Getting this:

```
Supabase CLI 1.110.1
Version 1.30.3 is already installed
Bundling dart_edge
Error bundling function: exit status 1                                                                  
file:///Users/andrey/Documents/MyProjects/Pillarium/pillarium_edge/supabase/functions/import_map.json   
file:///Users/andrey/Documents/MyProjects/Pillarium/pillarium_edge/supabase/functions/dart_edge/index.ts
error: Uncaught (in promise) Error: NotFound: No such file or directory (os error 2)                    
      const ret = new Error(getStringFromWasm0(arg0, arg1));                                            
                  ^                                                                                     
    at __wbg_new_8d2af00bc1e329ee (https://deno.land/x/eszip@v0.35.0/eszip_wasm.generated.js:513:19)    
    at <anonymous> (https://deno.land/x/eszip@v0.35.0/eszip_wasm_bg.wasm:1:1559899)                     
    at <anonymous> (https://deno.land/x/eszip@v0.35.0/eszip_wasm_bg.wasm:1:1398157)                     
    at <anonymous> (https://deno.land/x/eszip@v0.35.0/eszip_wasm_bg.wasm:1:1895031)                     
    at __wbg_adapter_40 (https://deno.land/x/eszip@v0.35.0/eszip_wasm.generated.js:229:6)               
    at real (https://deno.land/x/eszip@v0.35.0/eszip_wasm.generated.js:213:14)   
```

**Comment by venkata-reddy-dev** [comment]
@agordeev 

Please make sure to add `edge.yml` file under root directory. and mention projectPath as supabase as below.

And if you want to define multiple edge functions then define them as below.

```
supabase:
  functions:
    task1: 'lib/task1.dart'
    task2: 'lib/task2.dart'
  projectPath: "supabase"
```
